### ISSUE TITLE
FEATURE REQUEST: Execute command on ENTER (if possible)

### ISSUE THREAD

**Issue by SamClercky** [sudormrfbin/cheatsheet.nvim#2]
Hello @sudormrfbin ,

I really like your plugin and want to use it.

When looking at your plugin, I missed the feature where you could immediately execute the selected command or when the telescope window closes, I can't see the exact command anymore.

For this reason, I forked your plugin and implemented it myself but wasn't sure if you would want something like this since you already added a function to the ENTER key.

If you like my idea, I can do a pull request :smiley:

Sam Clercky

Ps. Repo: [https://github.com/SamClercky/cheatsheet.nvim](https://github.com/SamClercky/cheatsheet.nvim)

**Comment by sudormrfbin** [comment]
Hi !

Thanks for opening an issue. Please do open a PR. Printing it after selecting is a very good addition. For invoking commands on `Enter`, I see you're currently executing only the command without the arguments -- this would be inconsistent among different cheats since some commands an argument placeholder, like `:bufdo ‹Cmd›` and some others cheats have arguments that are required for the functionality mentioned in the description, like `:tab ball`.

A better approach here would be to pre-populate the command line with the full cheatcode and then letting the user modify it as required(or not at all) and press `Enter` again to execute it.
