### ISSUE TITLE
Dont show mappings for disabled plugins!

### ISSUE THREAD

**Issue by siduck76** [sudormrfbin/cheatsheet.nvim#8]
Hi @sudormrfbin , been liking cheatsheet.nvim so far :D. Is there any way to not show cheatsheet of disabled plugins? I have disabled some default plugins like netrw etc but they still show in the cheatsheet :(

**Comment by sudormrfbin** [comment]
Netrw is listed together with the default cheatsheet, and since you have [`default` as an enabled cheatsheet](https://github.com/NvChad/NvChad//blob/7753e03b9e561fa359912c1d632a5e69c035d90c/lua/plugins/chadsheet.lua#L19) in the config, netrw is also shown. Moving the netrw specific keys into it's own file should solve the problem.

**Comment by sudormrfbin** [comment]
Just pushed 7d83f02, could you check if it resolves the issue ?

**Comment by siduck76** [comment]
Lemme check!

**Comment by siduck76** [comment]
thanks this is fixed now :heart:
